### ISSUE TITLE
potential licence issue

### ISSUE THREAD

**Issue by danmarsden** [dualcube/moodle-enrol_braintree#2]
The licence for the braintree code included in the plugin appears to be the "Prior BSD License" and according to:
https://en.wikipedia.org/wiki/BSD_licenses

This version of the BSD licence is not compatible with the GPL (which Moodle and the other files in your plugin uses) - this will likely need resolving before we can include the plugin within the moodle plugins database.

**Comment by parthajeet** [comment]
We have checked and updated the licence. Looking forward to your response.

Regards,
Parthajeet~

**Comment by mudrd8mz** [comment]
Thanks. Checked against upstream https://github.com/braintree/braintree_php/blob/master/composer.json, the license is MIT.
